version: "3.8"

services:

  node:
    build:
      context: ./docker/development
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    networks:
      - api-network
    environment:
      - NODE_ENV=production
    command: "npm start"
    ports:
    - 3000:3000

  database:
    image: mariadb
    container_name: api-database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123
    volumes:
      - database:/var/lib/mysql
    networks:
      - api-network

volumes:
  database:
    external: true

networks:
  api-network:
    external: true